remote_theme: andywer/jekyll-docs-theme@v0.1.2

name: Shutter Packages
title: Shutter Packages

license:
  software: MIT License
  software_url: http://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      url: https://github.com/andywer/test

exclude:
  - Gemfile
  - Gemfile.lock
